graph TD
    main.js --> FoodTruck.js
    main.js --> TransientState.js
    FoodTruck.js --> Sales.js
    FoodTruck.js --> Entrees.js
    FoodTruck.js --> Vegetables.js
    FoodTruck.js --> SideDishes.js
    Entrees.js --> TransientState.js
    Vegetables.js --> TransientState.js
    SideDishes.js --> TransientState.js